cleaned Proceed() code

diff --git a/pacaur b/pacaur
--- a/pacaur
+++ b/pacaur
@@ -161,26 +161,6 @@ UpgradeAur() {
     timeout ${pkgs[@]}
 }
 
-Proceed() {
-    if [[ ! $noconfirm ]]; then
-        echo -ne "\nProceed with installation? [Y/n] "
-
-        read -n 1 yn
-        echo ""
-        case $yn in
-        [Yy]|[Yy]es|'')
-            return
-        ;;
-        *)
-            CleanUp ${deps[@]} &>/dev/null
-            exit
-        ;;
-        esac
-    else
-        echo ""
-    fi
-}
-
 CopyAbs() {
     for i in "$@"; do
         if [[ -e $buildDir/$i/PKGBUILD && ! $force ]]; then
@@ -195,23 +175,13 @@ CopyAbs() {
 EditPkgs() {
     if [[ $edit && ! $noedit ]]; then
         for i in "$@"; do
-
-            if [[ ! $edit || $option ]]; then
+            if [[ $option ]]; then
                 echo -ne "${colorB}::${reset} Edit ${colorW}$i${reset} PKGBUILD? [Y/n] "
-
-                read -n 1 yn
-                echo ""
-                case $yn in
-                [Yy]|[Yy]es|'')
-                    [[ -e $buildDir/$i/PKGBUILD ]] && $editor $buildDir/$i/PKGBUILD && success "${colorW}$i${reset} PKGBUILD edited" || error "Could not open ${colorW}$i${reset} PKGBUILD"
-                ;;
-                *)
+                if ! proceed; then
                     continue
-                esac
-
-            else
-                [[ -e $buildDir/$i/PKGBUILD ]] && $editor $buildDir/$i/PKGBUILD && success "${colorW}$i${reset} PKGBUILD edited" || error "Could not open ${colorW}$i${reset} PKGBUILD"
+                fi
             fi
+            [[ -e $buildDir/$i/PKGBUILD ]] && $editor $buildDir/$i/PKGBUILD && success "${colorW}$i${reset} PKGBUILD edited" || error "Could not open ${colorW}$i${reset} PKGBUILD"
         done
     fi
 }
@@ -229,11 +199,18 @@ CleanUp() {
 }
 
 MakePkgs() {
-    #info "AUR package(s) to build: ${colorW}${deps[@]}${reset}"
     echo -e "\n${colorY}AUR Targets (${#deps[@]}):${reset} ${deps[@]}"
+    echo ""
 
-    Proceed
+    if [[ ! $noconfirm ]]; then
+        echo -n "Proceed with installation? [Y/n] "
+        if ! proceed; then
+            CleanUp ${deps[@]} &>/dev/null
+            exit
+        fi
+    fi
 
+    #info "AUR package(s) to build: ${colorW}${deps[@]}${reset}"
     EditPkgs ${deps[@]}
 
     # reverse deps order
@@ -333,6 +310,15 @@ runasroot() {
         # echo hack to ensure all of the args get taken into account
         su root -c "$(echo $@)"
     fi
+}
+
+proceed() {
+    read -n 1 yn
+    echo ""
+    case $yn in
+        [Yy]|[Yy]es|'') return 0;;
+        *) return 1;;
+    esac
 }
 
 paraexec() {
