changed prompt text for install script

diff --git a/pacaur b/pacaur
--- a/pacaur
+++ b/pacaur
@@ -214,11 +214,11 @@ EditPkgs() {
             [[ -e $buildDir/$i/PKGBUILD ]] && source $buildDir/$i/PKGBUILD
             if [[ $install ]]; then
                 if [[ $option ]]; then
-                    if proceedY "${colorB}::${reset} Edit ${colorW}$i${reset} .install script?"; then
-                        [[ -e $buildDir/$i/$install ]] && $editor $buildDir/$i/$install && success "${colorW}$i${reset} install script edited" || error "Could not open ${colorW}$i${reset} install script"
+                    if proceedY "${colorB}::${reset} View ${colorW}$i${reset} .install script?"; then
+                        [[ -e $buildDir/$i/$install ]] && $editor $buildDir/$i/$install && success "${colorW}$i${reset} install script viewed" || error "Could not open ${colorW}$i${reset} install script"
                     fi
                 else
-                    [[ -e $buildDir/$i/$install ]] && $editor $buildDir/$i/$install && success "${colorW}$i${reset} install script edited" || error "Could not open ${colorW}$i${reset} install script"
+                    [[ -e $buildDir/$i/$install ]] && $editor $buildDir/$i/$install && success "${colorW}$i${reset} install script viewed" || error "Could not open ${colorW}$i${reset} install script"
                 fi
             fi
         fi
