check if pkgs exist in cache

diff --git a/pacaur b/pacaur
--- a/pacaur
+++ b/pacaur
@@ -215,13 +215,26 @@ MakePkgs() {
     [[ $color != true ]] && makeopts+=("--nocolor")
 
     for i in "${deps[@]}"; do
-        # build and install
-        if [ -e $buildDir/$i/PKGBUILD ]; then
-            info "Building ${colorW}$i${reset} package..."
-            cd $buildDir/$i
-            [[ $install ]] && makepkg -sfi ${makeopts[@]} --noconfirm || makepkg -sf ${makeopts[@]} --noconfirm
+        # check package cache
+        [[ $PKGDEST && ! $rebuild ]] && GetAurVersion $i && FindCachedPkg "$i-$Aversion"
+        if [[ $cachedpkg ]]; then
+            if [[ $install ]]; then
+                info "Installing ${colorW}$i${reset} cached package..."
+                runasroot $pacmanBin -U $cachedpkg ${pacopts[@]} --noconfirm
+            else
+                info "Package ${colorW}$i${reset} already available in cache"
+            fi
         else
-            error "Could not open ${colorW}$i${reset} PKGBUILD"
+
+            # build and install
+            if [ -e $buildDir/$i/PKGBUILD ]; then
+                info "Building ${colorW}$i${reset} package..."
+                cd $buildDir/$i
+                [[ $install ]] && makepkg -sfi ${makeopts[@]} --noconfirm || makepkg -sf ${makeopts[@]} --noconfirm
+            else
+                error "Could not open ${colorW}$i${reset} PKGBUILD"
+            fi
+
         fi
 
         # set dep status
@@ -267,6 +280,18 @@ CleanCache() {
     fi
 }
 
+GetAurVersion() {
+    Apkgver=$(grep '^pkgver' "$buildDir/$@/PKGBUILD" | cut -d '=' -f 2-)
+    Apkgrel=$(grep '^pkgrel' "$buildDir/$@/PKGBUILD" | cut -d '=' -f 2-)
+    Aversion=$Apkgver-$Apkgrel
+}
+
+FindCachedPkg() {
+    cachedpkg="$PKGDEST/$@-${CARCH}${PKGEXT}"
+    [[ ! -f "$cachedpkg" ]] && cachedpkg="$PKGDEST/$@-any${PKGEXT}"
+    [[ ! -f "$cachedpkg" ]] && cachedpkg=""
+}
+
 OutofdateChecks() {
     for i in ${deps[@]}; do
         DownloadJson $i &
@@ -287,10 +312,8 @@ ReinstallChecks() {
     if [[ ${exist[@]} ]]; then
         Qversion=($(expac -Q %v ${exist[@]}))
         for ((i=0; i<${#exist[@]}; i++)); do
-            Apkgver[$i]=$(grep '^pkgver' "$buildDir/${exist[$i]}/PKGBUILD" | cut -d '=' -f 2-)
-            Apkgrel[$i]=$(grep '^pkgrel' "$buildDir/${exist[$i]}/PKGBUILD" | cut -d '=' -f 2-)
-            Aversion[$i]=${Apkgver[$i]}-${Apkgrel[$i]}
-            [[ $(vercmp "${Aversion[$i]}" "${Qversion[$i]}") -gt 0 ]] && continue || warn "${exist[$i]}-${Qversion[$i]} is up to date -- reinstalling"
+            GetAurVersion ${exist[$i]}
+            [[ $(vercmp "$Aversion" "${Qversion[$i]}") -gt 0 ]] && continue || warn "${exist[$i]}-${Qversion[$i]} is up to date -- reinstalling"
         done
     fi
 }
@@ -436,6 +459,7 @@ usage() {
     echo "   --ignore        ignore a package upgrade (can be used more than once)"
     echo "   --noconfirm     do not prompt for any confirmation"
     echo "   --noedit        do not prompt to edit files"
+    echo "   --rebuild       always rebuild package"
     echo ""
     echo "general options:"
     echo "   -v, --version   display version information"
@@ -534,6 +558,7 @@ while [[ $1 ]]; do
         '--ignore') ignoredpkgs+=("$2"); ignorepkgs+=("--ignore" "$2"); shift;;
         '--noconfirm') noconfirm=true; pacopts+=("--noconfirm");;
         '--noedit') noedit=true;;
+        '--rebuild') rebuild=true;;
         -D* | '--database') runasroot $pacmanBin $@; exit;;
         -Q* | '--query') $pacmanBin $@; exit;;
         -R* | '--remove') runasroot $pacmanBin $@; exit;;
