simplified build directory cleaning message

diff --git a/pacaur b/pacaur
--- a/pacaur
+++ b/pacaur
@@ -174,7 +174,7 @@ CleanUp() {
         if [[ $count -ne 1 ]]; then
             # hack for cvs protected files
             chmod -R 755 $buildDir/* &>/dev/null
-            rm -r $buildDir/* &>/dev/null && success "Build directory ${colorW}$buildDir${reset} cleaned" || warn "Could not clean build directory ${colorW}$buildDir${reset}"
+            rm -r $buildDir/* &>/dev/null && success "Build directory cleaned" || warn "Could not clean build directory"
         fi
     fi
 }
